
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.setuptools]
packages = ["pyghm"]
package-dir = {"" = "src"}
include-package-data = true

[project.scripts]
pyghm = "pyghm.cli:cli"

[tool.pip-tools]
generate-hashes = true