
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.setuptools]
packages = ["pyghm"]
package-dir = {"" = "src"}
include-package-data = true


[project.scripts]
pyghm = "pyghm:main"

[tool.pip-tools]
generate-hashes = true
